### PR TITLE
Added support for christmas on Hypixel.

### PR DESCRIPTION
**Pull request by realwakils**
Currently the filter with mvps joining lobbies is not working, due to the fact that the join message changes during the christmas holidays.

### CODE REVIEW

**Comment by realwakils** [comment]
@boomboompower would it be possible for you to compile, because I'm facing some issues being unable to do it myself. Getting strange errors, something with incompatible gradle or something.
Thanks :)

**Comment by boomboompower** [comment]
@realwakils Yeah sure, I've fixed the CI and a build has been made at https://github.com/boomboompower/ToggleChat/releases/tag/3.0.28 ~ 

Can you show me the gradle error you've been getting? Is it related to lombok?

**Comment by realwakils** [comment]
@boomboompower Thanks and thanks for the quick reply.

I just cloned this project again and after running `./gradlew build`, it actually succesfully built this time? I did get this warning though: `Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.`. But idk if that's important.

Anyways, which IDE/code editor do you use for MC modding and which commands do you use to test, build etc.
I've coded a bunch of other stuff before (including MC plugins), but I'm quite new to MC modding.

**Comment by boomboompower** [comment]
@realwakils 

No worries, thanks for the commit!

I use IntelliJ for modding and other programming in Java. When making changes to the game, I find the plugin "MinecraftDev for IntelliJ" very useful
[IntelliJ](https://www.jetbrains.com/idea/) + [MinecraftDev](https://minecraftdev.org/)

Sometimes it can be useful to invalidate caches or use `./gradlew --refresh` (or `./gradlew --refresh-dependancies`) if you're having issues

You can ignore the warning, Forge uses it's own variation of Gradle

**Pull request merged**
